.. _area_selectors:

Reference Selection Keywords for AREA
+++++++++++++++++++++++++++++++++++++
CRDS selects appropriate AREA references based on the following keywords.
AREA is not applicable for instruments not in the table.
All keywords used for file selection are *required*.

========== =================================================================
Instrument Keywords                                                          
========== =================================================================
WFI        instrument, detector, date, time            
========== =================================================================

