Reference Selection Keywords for DARKDECAYSIGNAL
+++++++++++++++++++++++++++++++++++++++++++++++++
CRDS selects appropriate DARKDECAYSIGNAL references based on
the following keywords. DARKDECAYSIGNAL is not applicable for
instruments not in the table.
All keywords used for file selection are *required*.

========== ================================================
Instrument Keywords
========== ================================================
WFI        instrument, date, time
========== ================================================
