.. _flat_selectors:

Reference Selection Keywords for FLAT
+++++++++++++++++++++++++++++++++++++
CRDS selects appropriate FLAT references based on the following attributes.
FLAT is not applicable for instruments not in the table.
Non-standard attributes used for file selection are *required*.

========== ========================================================================
Instrument   Metadata
========== ========================================================================
WFI          instrument, detector, optical_element, date, time
========== ========================================================================
