.. _flat_selectors:

Reference Selection Keywords for FLAT
+++++++++++++++++++++++++++++++++++++
CRDS selects appropriate FLAT references based on the following keywords.
FLAT is not applicable for instruments not in the table.
Non-standard keywords used for file selection are *required*.

========== ========================================================================
Instrument Keywords                                                                 
========== ========================================================================
WFI        INSTRUME, DETECTOR, EXP_TYPE, FILTER, BAND, READPATT, GRATING
CGI        INSTRUME, DETECTOR, EXP_TYPE, FILTER, BAND, READPATT, GRATING
========== ========================================================================

