.. _integralnonlinearity_selectors:

Reference Selection Keywords for INTEGRALNONLINEARITY
+++++++++++++++++++++++++++++++++++++++++++++++++++++
CRDS selects appropriate INTEGRALNONLINEARITY references based on the
following keyword attributes.
All keyword attributes used for file selection are *required*.

========== =====================================
Instrument  Keyword Attributes
========== =====================================
WFI         instrument, detector, date, time
========== =====================================
