Reference Selection Keywords for LINEARITY and INVERSELINEARITY
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
CRDS selects appropriate LINEARITY and INVERSELINEARITY references based on the
following keyword attributes.
All keyword attributes used for file selection are *required*.

========== =====================================
Instrument  Keyword Attributes
========== =====================================
WFI         instrument, detector, date, time
========== =====================================
