.. _mask_selectors:

Reference Selection Keywords for MASK
+++++++++++++++++++++++++++++++++++++
CRDS selects appropriate MASK references based on the following keywords.
MASK is not applicable for instruments not in the table.

============ ==========================================================
 Instrument   Metadata
============ ==========================================================
 WFI	      instrument, detector, date, time
============ ==========================================================
