.. _photom_selectors:

Reference Selection Keywords for PHOTOM
+++++++++++++++++++++++++++++++++++++++
CRDS selects appropriate PHOTOM references based on the following keywords.
PHOTOM is not applicable for instruments not in the table.
All keywords used for file selection are *required*.

===============   ======================================  ==============
Attribute           Fully qualified path                   Instruments
===============   ======================================  ==============
detector           model.meta.instrument.detector          WFI
===============   ======================================  ==============
