.. _psf_selectors:

Reference Selection Keywords for PSFs
+++++++++++++++++++++++++++++++++++++++++++
CRDS selects appropriate PSF references based on the following metadata
attributes.
All attributes used for file selection are *required*.

========== ================================================
Instrument Keywords
========== ================================================
WFI	   instrument, detector, filter, date, time
========== ================================================
