.. _saturation_selectors:

Reference Selection Keywords for SATURATION
+++++++++++++++++++++++++++++++++++++++++++
CRDS selects appropriate SATURATION references based on the following metadata keywords.
All keywords used for file selection are *required*.

========== ================================================
Instrument Keywords                                         
========== ================================================
WFI	   instrument, detector, date, time
========== ================================================

