[tool.towncrier]
filename = "CHANGES.rst"
directory = "changes"
package = "romancal"
title_format = "{version} ({project_date})"
ignore = ["README.md"]
wrap = true
issue_format = "`#{issue} <https://github.com/spacetelescope/romancal/issues/{issue}>`_"

[[tool.towncrier.type]]
directory = "breaking"
name = "Breaking Changes"
showcontent = true

# general pipeline changes

[[tool.towncrier.type]]
directory = "stpipe"
name = "``stpipe``"
showcontent = true

[[tool.towncrier.type]]
directory = "associations"
name = "Associations"
showcontent = true

[[tool.towncrier.type]]
directory = "scripts"
name = "Scripts"
showcontent = true

[[tool.towncrier.type]]
directory = "exposure_pipeline"
name = "``exposure_pipeline``"
showcontent = true

[[tool.towncrier.type]]
directory = "mosaic_pipeline"
name = "``mosaic_pipeline``"
showcontent = true

[[tool.towncrier.type]]
directory = "skycell"
name = "``skycell``"
showcontent = true

# step changes

[[tool.towncrier.type]]
directory = "dq_init"
name = "``dq_init`` (WFI-Image, WFI-Prism, WFI-Grism)"
showcontent = true

[[tool.towncrier.type]]
directory = "saturation"
name = "``saturation`` (WFI-Image, WFI-Prism, WFI-Grism)"
showcontent = true

[[tool.towncrier.type]]
directory = "refpix"
name = "``refpix`` (WFI-Image, WFI-Prism, WFI-Grism)"
showcontent = true

[[tool.towncrier.type]]
directory = "dark_decay"
name = "``dark_decay`` (WFI-Image, WFI-Prism, WFI-Grism)"
showcontent = true

[[tool.towncrier.type]]
directory = "wfi18_transient"
name = "``wfi18_transient`` (WFI-Image, WFI-Prism, WFI-Grism)"
showcontent = true

[[tool.towncrier.type]]
directory = "linearity"
name = "``linearity`` (WFI-Image, WFI-Prism, WFI-Grism)"
showcontent = true

[[tool.towncrier.type]]
directory = "dark_current"
name = "``dark_current`` (WFI-Image, WFI-Prism, WFI-Grism)"
showcontent = true

[[tool.towncrier.type]]
directory = "jump_detection"
name = "``jump_detection``"
showcontent = true

[[tool.towncrier.type]]
directory = "orientation"
name = "``orientation``"
showcontent = true

[[tool.towncrier.type]]
directory = "ramp_fitting"
name = "``ramp_fitting`` (WFI-Image, WFI-Prism, WFI-Grism)"
showcontent = true

[[tool.towncrier.type]]
directory = "assign_wcs"
name = "``assign_wcs`` (WFI-Image, WFI-Prism, WFI-Grism)"
showcontent = true

[[tool.towncrier.type]]
directory = "flatfield"
name = "``flatfield`` (WFI-Image)"
showcontent = true

[[tool.towncrier.type]]
directory = "photom"
name = "``photom`` (WFI-Image)"
showcontent = true

[[tool.towncrier.type]]
directory = "flux"
name = "``flux``"
showcontent = true

[[tool.towncrier.type]]
directory = "source_detection"
name = "``source_detection`` (WFI-Image)"
showcontent = true

[[tool.towncrier.type]]
directory = "tweakreg"
name = "``tweakreg`` (WFI-Image)"
showcontent = true

[[tool.towncrier.type]]
directory = "skymatch"
name = "``skymatch``"
showcontent = true

[[tool.towncrier.type]]
directory = "outlier_detection"
name = "``outlier_detection``"
showcontent = true

[[tool.towncrier.type]]
directory = "resample"
name = "``resample``"
showcontent = true

[[tool.towncrier.type]]
directory = "source_catalog"
name = "``source_catalog``"
showcontent = true

[[tool.towncrier.type]]
directory = "multiband_catalog"
name = "``multiband_catalog``"
showcontent = true

# other changes

[[tool.towncrier.type]]
directory = "general"
name = "General"
showcontent = true

[[tool.towncrier.type]]
directory = "docs"
name = "Documentation"
showcontent = true
