
Standard ASDF metadata tags
+++++++++++++++++++++++++++
The following table lists the tags that are *required* to be present
in all reference files.  The first column gives meta tag in ASDF
reference file headers, which is the same as the name within the data
model meta tree (second column).  The second column gives the roman
data model name for each keyword, which is useful when using data
models in creating and populating a new reference file.

============  ========================
Attribute      Fully Qualified Path
============  ========================

**NOTE:** More information on standard required keywords can be found here:
:ref:`Standard Required Keywords`
