#
# Roman documentation build configuration file
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import datetime
import importlib
import io
import os
import tomllib
from contextlib import contextmanager, redirect_stdout
from pathlib import Path

import docutils
from docutils.parsers.rst import Directive
from roman_datamodels import datamodels as rdm
from roman_datamodels import get_latest_schema
from sphinx.directives.code import CodeBlock
from sphinx.ext.autodoc import AttributeDocumenter

from romancal.stpipe import RomanStep


@contextmanager
def stdout_as_string_io():
    f = io.StringIO()
    with redirect_stdout(f):
        yield f


class ImageModelInfoDirective(CodeBlock):
    def run(self):
        example_image_model = rdm.ImageModel.create_fake_data()
        with stdout_as_string_io() as sio:
            example_image_model.info()
        self.arguments = ["python"]
        self.content = [
            ">>> image_model.info()",
            sio.getvalue(),
        ]
        return super().run()


class ImageModelSearchDirective(CodeBlock):
    def run(self):
        example_image_model = rdm.ImageModel.create_fake_data()
        with stdout_as_string_io() as sio:
            print(example_image_model.search("detector"))
        self.arguments = ["python"]
        self.content = [
            ">>> image_model.search('detector')",
            sio.getvalue(),
        ]
        return super().run()


class SourceCatalogColumnsDirective(Directive):
    def run(self):
        node = docutils.nodes.paragraph()
        node.parent = self.state.parent

        _, schema = get_latest_schema(
            "asdf://stsci.edu/datamodels/roman/schemas/tables/source_catalog_columns"
        )
        defs = schema["definitions"]
        column_names = sorted(defs.keys())

        rows = [
            {
                "name": name,
                "unit": defs[name].get("unit", ""),
                "description": defs[name]["description"],
            }
            for name in column_names
        ]

        table_columns = ("name", "unit", "description")
        column_widths = {
            name: max(len(name), max(len(r[name]) for r in rows))
            for name in table_columns
        }

        header = " ".join("".ljust(column_widths[c], "=") for c in table_columns)
        titles = " ".join(c.capitalize().ljust(column_widths[c]) for c in table_columns)

        node.children.append(header)
        node.children.append(titles)
        node.children.append(header)

        for row in rows:
            row_text = " ".join(row[c].ljust(column_widths[c]) for c in table_columns)
            node.children.append(row_text)

        node.children.append(header)

        output_node = docutils.nodes.paragraph()
        self.state.nested_parse(node, 0, output_node)
        return [output_node]


class StepSpecDocumenter(AttributeDocumenter):
    def should_suppress_value_header(self):
        if self.name == "spec" and issubclass(self.parent, RomanStep):
            # if this attribute is named "spec" and belongs to a "Step"
            # don't show the value, it will be formatted in add_context below
            return True
        return super().should_suppress_value_header()

    def add_content(self, more_content):
        super().add_content(more_content)
        if self.name != "spec" or not issubclass(self.parent, RomanStep):
            return
        if not self.object.strip():
            return

        # format the long "Step.spec" string to improve readability
        source_name = self.get_sourcename()
        self.add_line("::", source_name, 0)
        self.add_line("  ", source_name, 1)
        txt = "\n".join(l.strip() for l in self.object.strip().splitlines())
        self.add_line(f"  {txt}", source_name, 2)


def register_step_spec_documenter(app, config):
    # add a custom AttributeDocumenter subclass to handle Step.spec formatting
    app.add_autodocumenter(StepSpecDocumenter, True)


def setup(app):
    try:
        app.add_css_file("stsci.css")
    except AttributeError:
        app.add_stylesheet("stsci.css")
    # register with a high priority to override the autodoc documenter
    app.connect("config-inited", register_step_spec_documenter, priority=9000)
    app.add_directive("image_model_info", ImageModelInfoDirective)
    app.add_directive("image_model_search", ImageModelSearchDirective)
    app.add_directive("source_catalog_columns", SourceCatalogColumnsDirective)


# -- General configuration ------------------------------------------------
with open(Path(__file__).parent.parent / "pyproject.toml", "rb") as configuration_file:
    conf = tomllib.load(configuration_file)
setup_cfg = conf["project"]


on_rtd = os.environ.get("READTHEDOCS", None) == "True"


# Configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    "python": ("https://docs.python.org/3/", None),
    "numpy": ("https://numpy.org/devdocs", None),
    "scipy": ("https://scipy.github.io/devdocs", None),
    "matplotlib": ("https://matplotlib.org/", None),
    "gwcs": ("https://gwcs.readthedocs.io/en/latest/", None),
    "astropy": ("https://docs.astropy.org/en/stable/", None),
    "photutils": ("https://photutils.readthedocs.io/en/stable/", None),
    "roman_datamodels": ("https://roman-datamodels.readthedocs.io/en/latest/", None),
    "rad": ("https://rad.readthedocs.io/en/latest/", None),
    "drizzle": ("https://spacetelescope-drizzle.readthedocs.io/en/latest/", None),
    "stcal": ("https://stcal.readthedocs.io/en/latest/", None),
    "stpipe": ("https://stpipe.readthedocs.io/en/latest/", None),
}

intersphinx_disabled_reftypes = ["*"]


# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "pytest_doctestplus.sphinx.doctestplus",
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.inheritance_diagram",
    "sphinx.ext.viewcode",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    "sphinx_automodapi.automodapi",
    "sphinx_automodapi.automodsumm",
    "sphinx_automodapi.autodoc_enhancements",
    "sphinx_automodapi.smart_resolver",
    "sphinxcontrib.jquery",
]

if on_rtd:
    extensions.append("sphinx.ext.mathjax")
else:
    extensions.append("sphinx.ext.imgmath")

# Add any paths that contain templates here, relative to this directory.
# templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = "index"

# A list of warning types to suppress arbitrary warning messages.
suppress_warnings = [
    "app.add_directive",
]

# General information about the project
project = setup_cfg["name"]
author = setup_cfg["authors"][0]["name"]
copyright = f"{datetime.datetime.now().year}, {author}"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
package = importlib.import_module(setup_cfg["name"])
try:
    version = package.__version__.split("-", 1)[0]
    # The full version, including alpha/beta/rc tags.
    release = package.__version__
except AttributeError:
    version = "dev"
    release = "dev"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ["_build"]

# This is added to the end of RST files - a good place to put substitutions to
# be used globally.
rst_epilog = """.. _romancal: high-level_API.html"""

# The reST default role (used for this markup: `text`) to use for all
# documents.
default_role = "obj"

# Don't show summaries of the members in each class along with the
# class' docstring
numpydoc_show_class_members = False

autosummary_generate = True

automodapi_toctreedirnm = "api"

# Class documentation should contain *both* the class docstring and
# the __init__ docstring
autoclass_content = "both"

# Render inheritance diagrams in SVG
graphviz_output_format = "svg"

graphviz_dot_args = [
    "-Nfontsize=10",
    "-Nfontname=Helvetica Neue, Helvetica, Arial, sans-serif",
    "-Efontsize=10",
    "-Efontname=Helvetica Neue, Helvetica, Arial, sans-serif",
    "-Gfontsize=10",
    "-Gfontname=Helvetica Neue, Helvetica, Arial, sans-serif",
]

# activate figure numbering
numfig = True
# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "default"

# Mapping for links to the ASDF Standard in ASDF schema documentation
asdf_schema_reference_mappings = [
    (
        "tag:stsci.edu:asdf",
        "https://asdf-standard.readthedocs.io/en/latest/generated/stsci.edu/asdf/",
    ),
]

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "sphinx_rtd_theme"
html_logo = "_static/roman_logo_white_w100px.png"
html_favicon = "_static/favicon.ico"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.

html_theme_options = {"collapse_navigation": True}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
html_last_updated_fmt = "%b %d, %Y"

# Custom sidebar templates, maps document names to template names.
html_sidebars = {"**": ["globaltoc.html", "relations.html", "searchbox.html"]}

# If false, no module index is generated.
html_domain_indices = True

# If false, no index is generated.
html_use_index = True

# Output file base name for HTML help builder.
htmlhelp_basename = "romandoc"

# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [("index", "romancal", "Roman Pipeline Documentation", ["romancal"], 1)]

# If true, show URL addresses after external links.
man_show_urls = True

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        "index",
        "romancal",
        "Roman Pipeline Documentation",
        "romancal",
        "romancal",
        "Roman Pipeline Documentation",
        "Miscellaneous",
    ),
]

# If false, no module index is generated.
texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
texinfo_show_urls = "inline"

# -- Options for Epub output ----------------------------------------------

# Bibliographic Dublin Core info.
epub_title = "Roman"
epub_author = "STSCI"
epub_publisher = "STSCI"
epub_copyright = "2017, AURA"

# The HTML theme for the epub output. Since the default themes are not
# optimized for small screen space, using the same theme for HTML and
# epub output is usually not wise. This defaults to 'epub', a theme designed
# to save visual space.
epub_theme = "epub"

# A list of files that should not be packed into the epub file.
epub_exclude_files = ["search.html"]
