name: build

on:
  release:
    types: [ released ]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: check that `requirements-sdp.txt` is populated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # v4.2.0
      - if: github.event_name == 'release'
        run: grep -v '^ *#' requirements-sdp.txt
  build:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@924441154cf3053034c6513d5e06c69d262fb9a6  # v1.13.0
    needs: [ check ]
    with:
      upload_to_pypi: ${{ (github.event_name == 'release') && (github.event.action == 'released') }}
    secrets:
      pypi_token: ${{ secrets.PYPI_PASSWORD_STSCI_MAINTAINER }}
